In [2]:
import numpy as np
numbers = [1, 2, 3, 4]
arr_numbers = np.array(numbers)
print(numbers, arr_numbers, sep='\n')

[1, 2, 3, 4]
[1 2 3 4]


In [9]:
numbers = list(range(10, 20))
print(numbers)
arr_numbers = np.arange(10, 20)
print(arr_numbers)
arr_numbers = np.arange(10, 20, 2)
print(arr_numbers)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [17]:
arr_numbers = np.linspace(0, 1, 10, endpoint=False)
print(arr_numbers)
arr_numbers = np.linspace(10, 20, 5, endpoint=False, dtype=int)
print(arr_numbers)
arr_numbers = np.linspace(11, 19, 5, dtype=int)
print(arr_numbers)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[10 12 14 16 18]
[11 13 15 17 19]


In [20]:
a = np.zeros(5)
print(a)
b = np.ones(10, dtype=int)
print(b)
c = b * 2
print(c)

[0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]


In [22]:
b = [1, 1, 1, 1]
c = b * 2
ast = '*' * 10
print(ast)
print(c)

**********
[1, 1, 1, 1, 1, 1, 1, 1]


In [26]:
a = np.linspace(0, 1, 10, endpoint=False)
print(a)
b = np.sin(a) + np.cos(a)
print(b)
c = b - a
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[1.         1.09483758 1.17873591 1.2508567  1.31047934 1.3570081
 1.38997809 1.40905987 1.4140628  1.40493688]
[1.         0.99483758 0.97873591 0.9508567  0.91047934 0.8570081
 0.78997809 0.70905987 0.6140628  0.50493688]
