In [1]:
import numpy as np

In [ ]:
# create array from list
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(np.shape(matrix))
a = np.array([1, 2, 3, 4])
print(a, np.shape(a))
b = np.reshape(a, (4, 1))
c = np.reshape(a, (1, 4))
print(b, np.shape(b))
print(c, np.shape(c))
d = np.reshape(a, (2, 2))
print(d, np.shape(d))

In [8]:
matrix = np.reshape(np.random.randint(10, 100, 12), (3, 4))
print(matrix)

[[27 83 16 48]
 [82 23 12 22]
 [48 49 85 85]]


In [9]:
print(matrix[1][2])
print(matrix[1, 2])

12
12


In [10]:
# Get 2 last row
print(matrix[1:])

[[82 23 12 22]
 [48 49 85 85]]


In [11]:
# Get 2 last rows, 2 first columns
print(matrix[1:, :2])

[[82 23]
 [48 49]]


In [14]:
print(matrix[:2, 1:3])
print(matrix[:, -2:])

[[83 16]
 [23 12]]
[[16 48]
 [12 22]
 [85 85]]
