In [3]:
import numpy as np

In [ ]:
a = np.ones(64, dtype=int)
a = np.reshape(a, (8, 8))
a[1:-1, 1:-1] = 0
print(a)

In [ ]:
a = np.reshape(np.zeros(64, dtype=int), (8, 8))
a[0, :] = 1
a[-1, :] = 1
a[:, 0] = 1
a[:, -1] = 1
print(a)

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[0::2]
c = a[1::2]
a[::2] = 0
print(b, c, a)

[0 0 0] [2 4 6] [0 2 0 4 0 6]


In [13]:
# Question b
b = np.reshape(np.ones(64, dtype=int), (8, 8))
b[::2, 1::2] = 0
b[1::2, ::2] = 0
print(b)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
# Question c
c = np.reshape(np.random.randint(10, 100, 64, dtype=int), (8, 8))
c[c%3!=0] = c[c%3!=0] * -1
print(c)

[[ 87  24 -65  48  30  12 -40 -52]
 [ 42 -46 -67 -23 -88 -76 -88  12]
 [-88 -67 -20 -47 -53 -25 -44 -98]
 [-41 -98 -88 -26 -97 -74  78 -25]
 [ 57 -25 -59  48 -97 -44 -43 -64]
 [-77 -55  81 -61  21 -64  75 -74]
 [-34 -80 -56 -59  72 -11 -58  30]
 [-14  87 -77 -32 -58  42  84 -50]]
