In [1]:
import numpy as np

In [6]:
numbers = np.random.randint(10, 100, 10)
print(numbers)

[27 34 62 77 33 98 37 70 14 83]


In [7]:
b_index = numbers % 2 == 1 
print(b_index)

[ True False False  True  True False  True False False  True]


In [8]:
odds = numbers[b_index]
print(odds)

[27 77 33 37 83]


In [9]:
numbers[b_index] = 0
print(numbers)

[ 0 34 62  0  0 98  0 70 14  0]


In [10]:
numbers = np.random.randint(-99, 100, 20)
print(numbers)

[ 53  70  80  62 -84  54 -94 -42  61  79  53  34 -98  69 -76  14  69  34
  91 -78]


In [14]:
# 1. Lọc ra những số dương
positives = numbers[numbers > 0]
print(positives)
# 2. Lọc ra những số âm
negatives = numbers[numbers < 0]
print(negatives)
# 3. Đổi số âm thành số dương
pos_nums = negatives * -1
print(pos_nums)
print(numbers)
numbers[numbers < 0] *= -1
# a =  a * -1 => a *= -1
# numbers[numbers < 0] = numbers[numbers < 0] * -1
print(numbers)
# Old style
for n in numbers:
    if n < 0:
        n += -1

[53 70 80 62 54 61 79 53 34 69 14 69 34 91]
[-84 -94 -42 -98 -76 -78]
[84 94 42 98 76 78]
[ 53  70  80  62 -84  54 -94 -42  61  79  53  34 -98  69 -76  14  69  34
  91 -78]
[53 70 80 62 84 54 94 42 61 79 53 34 98 69 76 14 69 34 91 78]


In [17]:
a = int(input('Enter a: '))
b = int(input('Enter b:'))
# Old style
if a > b:
    max2so = a
else:
    max2so = b
print(max2so)

8


In [19]:
max2so = a if a > b else b
print(max2so)
print('Max 2 so:', a if a > b else b)

8
Max 2 so: 8
